name: Build AltServer

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Compile
        run: docker buildx build --platform linux/${{ matrix.platform }} -f buildenv/Dockerfile --output build .
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AltServer-${{ matrix.platform }}
          path: build/*